library(XML)

dataset <- read.csv(file.choose())

mean(dataset$Points)
mean(dataset$Score)
mean(dataset$Weigh)
median(dataset$Points)
median(dataset$Score)
median(dataset$Weigh)
mode(dataset$Points)
mode(dataset$Score)
mode(dataset$Weigh)
var(dataset$Points)
var(dataset$Score)
var(dataset$Weigh)
range(dataset$Points)
range(dataset$Score)
range(dataset$Weigh)
sd(dataset$Points)
sd(dataset$Score)
sd(dataset$Weigh)
